rhel8 --> rhel9
mitre/saf-training pull request #298
Opened 2024-12-12 18:34 UTC by wdower

2024-12-12 22:58 UTC, aaronlippold approved these changes

2024-12-14 17:09 UTC, Amndeep7 requested changes

2024-12-14 17:09 UTC, Amndeep7 commented on src/courses/advanced/03.md
> +You should have an inputs file in your profile, at `my_nginx/inputs.yml`. It should say the following:
```suggestion
You should have an inputs file in your profile at `my_nginx/inputs.yml`. It should say the following:
```

2024-12-14 17:09 UTC, Amndeep7 approved these changes

2024-12-14 17:12 UTC, merged